//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSAPI
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallMethodResult", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DMSAPI.CallMethodParams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DMSAPI.DocObj))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DMSAPI.FileObj[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DMSAPI.FileObj))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DMSAPI.PLMDocObj))]
    public partial class CallMethodResult : object
    {
        
        private bool SuccessField;
        
        private string MessageField;
        
        private object OptionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public object Options
        {
            get
            {
                return this.OptionsField;
            }
            set
            {
                this.OptionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallMethodParams", Namespace="http://tempuri.org/")]
    public partial class CallMethodParams : object
    {
        
        private string testField;
        
        private string TokenField;
        
        private string MethodField;
        
        private string OptionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string test
        {
            get
            {
                return this.testField;
            }
            set
            {
                this.testField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Method
        {
            get
            {
                return this.MethodField;
            }
            set
            {
                this.MethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Options
        {
            get
            {
                return this.OptionsField;
            }
            set
            {
                this.OptionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocObj", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DMSAPI.PLMDocObj))]
    public partial class DocObj : object
    {
        
        private string numField;
        
        private string doc_noField;
        
        private string doc_nameField;
        
        private string stateField;
        
        private string writerField;
        
        private string sec_levelField;
        
        private string sec_level_nameField;
        
        private string doc_typeField;
        
        private string descriptionField;
        
        private string attach_typeField;
        
        private int version_majorField;
        
        private int version_minorField;
        
        private string versionField;
        
        private bool to_pdfField;
        
        private bool delete_flagField;
        
        private System.Nullable<System.DateTime> effective_dateField;
        
        private System.Nullable<System.DateTime> expire_dateField;
        
        private string change_descField;
        
        private System.DateTime create_dateField;
        
        private string create_userField;
        
        private System.DateTime update_dateField;
        
        private string update_userField;
        
        private string virtual_pathField;
        
        private bool isChangeVersionField;
        
        private int lastVersion_majorField;
        
        private int lastVersion_minorField;
        
        private string dms_style_dataField;
        
        private string extField;
        
        private int folder_idField;
        
        private int doc_idField;
        
        private DMSAPI.FileObj[] FilesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string num
        {
            get
            {
                return this.numField;
            }
            set
            {
                this.numField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string doc_no
        {
            get
            {
                return this.doc_noField;
            }
            set
            {
                this.doc_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string doc_name
        {
            get
            {
                return this.doc_nameField;
            }
            set
            {
                this.doc_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string writer
        {
            get
            {
                return this.writerField;
            }
            set
            {
                this.writerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sec_level
        {
            get
            {
                return this.sec_levelField;
            }
            set
            {
                this.sec_levelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sec_level_name
        {
            get
            {
                return this.sec_level_nameField;
            }
            set
            {
                this.sec_level_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string doc_type
        {
            get
            {
                return this.doc_typeField;
            }
            set
            {
                this.doc_typeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string attach_type
        {
            get
            {
                return this.attach_typeField;
            }
            set
            {
                this.attach_typeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int version_major
        {
            get
            {
                return this.version_majorField;
            }
            set
            {
                this.version_majorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int version_minor
        {
            get
            {
                return this.version_minorField;
            }
            set
            {
                this.version_minorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool to_pdf
        {
            get
            {
                return this.to_pdfField;
            }
            set
            {
                this.to_pdfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool delete_flag
        {
            get
            {
                return this.delete_flagField;
            }
            set
            {
                this.delete_flagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.Nullable<System.DateTime> effective_date
        {
            get
            {
                return this.effective_dateField;
            }
            set
            {
                this.effective_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.Nullable<System.DateTime> expire_date
        {
            get
            {
                return this.expire_dateField;
            }
            set
            {
                this.expire_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string change_desc
        {
            get
            {
                return this.change_descField;
            }
            set
            {
                this.change_descField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.DateTime create_date
        {
            get
            {
                return this.create_dateField;
            }
            set
            {
                this.create_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string create_user
        {
            get
            {
                return this.create_userField;
            }
            set
            {
                this.create_userField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public System.DateTime update_date
        {
            get
            {
                return this.update_dateField;
            }
            set
            {
                this.update_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string update_user
        {
            get
            {
                return this.update_userField;
            }
            set
            {
                this.update_userField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string virtual_path
        {
            get
            {
                return this.virtual_pathField;
            }
            set
            {
                this.virtual_pathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public bool isChangeVersion
        {
            get
            {
                return this.isChangeVersionField;
            }
            set
            {
                this.isChangeVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public int lastVersion_major
        {
            get
            {
                return this.lastVersion_majorField;
            }
            set
            {
                this.lastVersion_majorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=25)]
        public int lastVersion_minor
        {
            get
            {
                return this.lastVersion_minorField;
            }
            set
            {
                this.lastVersion_minorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string dms_style_data
        {
            get
            {
                return this.dms_style_dataField;
            }
            set
            {
                this.dms_style_dataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string ext
        {
            get
            {
                return this.extField;
            }
            set
            {
                this.extField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=28)]
        public int folder_id
        {
            get
            {
                return this.folder_idField;
            }
            set
            {
                this.folder_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public int doc_id
        {
            get
            {
                return this.doc_idField;
            }
            set
            {
                this.doc_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public DMSAPI.FileObj[] Files
        {
            get
            {
                return this.FilesField;
            }
            set
            {
                this.FilesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileObj", Namespace="http://tempuri.org/")]
    public partial class FileObj : object
    {
        
        private int folder_idField;
        
        private int doc_idField;
        
        private int version_majorField;
        
        private int version_minorField;
        
        private string file_idField;
        
        private long sizeField;
        
        private string size_unitField;
        
        private string extField;
        
        private string pdf_fileField;
        
        private string shadow_fileField;
        
        private bool delete_flagField;
        
        private System.DateTime create_dateField;
        
        private string create_userField;
        
        private System.DateTime update_dateField;
        
        private string update_userField;
        
        private string origin_fileField;
        
        private string contentField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int folder_id
        {
            get
            {
                return this.folder_idField;
            }
            set
            {
                this.folder_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int doc_id
        {
            get
            {
                return this.doc_idField;
            }
            set
            {
                this.doc_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int version_major
        {
            get
            {
                return this.version_majorField;
            }
            set
            {
                this.version_majorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int version_minor
        {
            get
            {
                return this.version_minorField;
            }
            set
            {
                this.version_minorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string file_id
        {
            get
            {
                return this.file_idField;
            }
            set
            {
                this.file_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public long size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string size_unit
        {
            get
            {
                return this.size_unitField;
            }
            set
            {
                this.size_unitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ext
        {
            get
            {
                return this.extField;
            }
            set
            {
                this.extField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string pdf_file
        {
            get
            {
                return this.pdf_fileField;
            }
            set
            {
                this.pdf_fileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string shadow_file
        {
            get
            {
                return this.shadow_fileField;
            }
            set
            {
                this.shadow_fileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool delete_flag
        {
            get
            {
                return this.delete_flagField;
            }
            set
            {
                this.delete_flagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime create_date
        {
            get
            {
                return this.create_dateField;
            }
            set
            {
                this.create_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string create_user
        {
            get
            {
                return this.create_userField;
            }
            set
            {
                this.create_userField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.DateTime update_date
        {
            get
            {
                return this.update_dateField;
            }
            set
            {
                this.update_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string update_user
        {
            get
            {
                return this.update_userField;
            }
            set
            {
                this.update_userField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string origin_file
        {
            get
            {
                return this.origin_fileField;
            }
            set
            {
                this.origin_fileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PLMDocObj", Namespace="http://tempuri.org/")]
    public partial class PLMDocObj : DMSAPI.DocObj
    {
        
        private string folderPathField;
        
        private string recallField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string folderPath
        {
            get
            {
                return this.folderPathField;
            }
            set
            {
                this.folderPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string recall
        {
            get
            {
                return this.recallField;
            }
            set
            {
                this.recallField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DMSAPI.APISoap")]
    public interface APISoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<DMSAPI.HelloWorldResponse> HelloWorldAsync(DMSAPI.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<DMSAPI.LoginResponse> LoginAsync(DMSAPI.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<DMSAPI.LogoutResponse> LogoutAsync(DMSAPI.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CallMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<DMSAPI.CallMethodResponse> CallMethodAsync(DMSAPI.CallMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CallMethodByString", ReplyAction="*")]
        System.Threading.Tasks.Task<DMSAPI.CallMethodByStringResponse> CallMethodByStringAsync(DMSAPI.CallMethodByStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewDocObj", ReplyAction="*")]
        System.Threading.Tasks.Task<DMSAPI.GetNewDocObjResponse> GetNewDocObjAsync(DMSAPI.GetNewDocObjRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PLMDocObjClass", ReplyAction="*")]
        System.Threading.Tasks.Task<DMSAPI.PLMDocObjClassResponse> PLMDocObjClassAsync(DMSAPI.PLMDocObjClassRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public DMSAPI.HelloWorldRequestBody Body;
        
        public HelloWorldRequest()
        {
        }
        
        public HelloWorldRequest(DMSAPI.HelloWorldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody
    {
        
        public HelloWorldRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public DMSAPI.HelloWorldResponseBody Body;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(DMSAPI.HelloWorldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody()
        {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public DMSAPI.LoginRequestBody Body;
        
        public LoginRequest()
        {
        }
        
        public LoginRequest(DMSAPI.LoginRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody()
        {
        }
        
        public LoginRequestBody(string userid, string password)
        {
            this.userid = userid;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public DMSAPI.LoginResponseBody Body;
        
        public LoginResponse()
        {
        }
        
        public LoginResponse(DMSAPI.LoginResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DMSAPI.CallMethodResult LoginResult;
        
        public LoginResponseBody()
        {
        }
        
        public LoginResponseBody(DMSAPI.CallMethodResult LoginResult)
        {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logout", Namespace="http://tempuri.org/", Order=0)]
        public DMSAPI.LogoutRequestBody Body;
        
        public LogoutRequest()
        {
        }
        
        public LogoutRequest(DMSAPI.LogoutRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public LogoutRequestBody()
        {
        }
        
        public LogoutRequestBody(string token)
        {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutResponse", Namespace="http://tempuri.org/", Order=0)]
        public DMSAPI.LogoutResponseBody Body;
        
        public LogoutResponse()
        {
        }
        
        public LogoutResponse(DMSAPI.LogoutResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DMSAPI.CallMethodResult LogoutResult;
        
        public LogoutResponseBody()
        {
        }
        
        public LogoutResponseBody(DMSAPI.CallMethodResult LogoutResult)
        {
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallMethodRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallMethod", Namespace="http://tempuri.org/", Order=0)]
        public DMSAPI.CallMethodRequestBody Body;
        
        public CallMethodRequest()
        {
        }
        
        public CallMethodRequest(DMSAPI.CallMethodRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CallMethodRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DMSAPI.CallMethodParams Params;
        
        public CallMethodRequestBody()
        {
        }
        
        public CallMethodRequestBody(DMSAPI.CallMethodParams Params)
        {
            this.Params = Params;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallMethodResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallMethodResponse", Namespace="http://tempuri.org/", Order=0)]
        public DMSAPI.CallMethodResponseBody Body;
        
        public CallMethodResponse()
        {
        }
        
        public CallMethodResponse(DMSAPI.CallMethodResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CallMethodResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DMSAPI.CallMethodResult CallMethodResult;
        
        public CallMethodResponseBody()
        {
        }
        
        public CallMethodResponseBody(DMSAPI.CallMethodResult CallMethodResult)
        {
            this.CallMethodResult = CallMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallMethodByStringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallMethodByString", Namespace="http://tempuri.org/", Order=0)]
        public DMSAPI.CallMethodByStringRequestBody Body;
        
        public CallMethodByStringRequest()
        {
        }
        
        public CallMethodByStringRequest(DMSAPI.CallMethodByStringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CallMethodByStringRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public CallMethodByStringRequestBody()
        {
        }
        
        public CallMethodByStringRequestBody(string str)
        {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallMethodByStringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallMethodByStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public DMSAPI.CallMethodByStringResponseBody Body;
        
        public CallMethodByStringResponse()
        {
        }
        
        public CallMethodByStringResponse(DMSAPI.CallMethodByStringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CallMethodByStringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DMSAPI.CallMethodResult CallMethodByStringResult;
        
        public CallMethodByStringResponseBody()
        {
        }
        
        public CallMethodByStringResponseBody(DMSAPI.CallMethodResult CallMethodByStringResult)
        {
            this.CallMethodByStringResult = CallMethodByStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewDocObjRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewDocObj", Namespace="http://tempuri.org/", Order=0)]
        public DMSAPI.GetNewDocObjRequestBody Body;
        
        public GetNewDocObjRequest()
        {
        }
        
        public GetNewDocObjRequest(DMSAPI.GetNewDocObjRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNewDocObjRequestBody
    {
        
        public GetNewDocObjRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewDocObjResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewDocObjResponse", Namespace="http://tempuri.org/", Order=0)]
        public DMSAPI.GetNewDocObjResponseBody Body;
        
        public GetNewDocObjResponse()
        {
        }
        
        public GetNewDocObjResponse(DMSAPI.GetNewDocObjResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewDocObjResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DMSAPI.DocObj GetNewDocObjResult;
        
        public GetNewDocObjResponseBody()
        {
        }
        
        public GetNewDocObjResponseBody(DMSAPI.DocObj GetNewDocObjResult)
        {
            this.GetNewDocObjResult = GetNewDocObjResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PLMDocObjClassRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PLMDocObjClass", Namespace="http://tempuri.org/", Order=0)]
        public DMSAPI.PLMDocObjClassRequestBody Body;
        
        public PLMDocObjClassRequest()
        {
        }
        
        public PLMDocObjClassRequest(DMSAPI.PLMDocObjClassRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PLMDocObjClassRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DMSAPI.PLMDocObj plmDoc;
        
        public PLMDocObjClassRequestBody()
        {
        }
        
        public PLMDocObjClassRequestBody(DMSAPI.PLMDocObj plmDoc)
        {
            this.plmDoc = plmDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PLMDocObjClassResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PLMDocObjClassResponse", Namespace="http://tempuri.org/", Order=0)]
        public DMSAPI.PLMDocObjClassResponseBody Body;
        
        public PLMDocObjClassResponse()
        {
        }
        
        public PLMDocObjClassResponse(DMSAPI.PLMDocObjClassResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PLMDocObjClassResponseBody
    {
        
        public PLMDocObjClassResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface APISoapChannel : DMSAPI.APISoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class APISoapClient : System.ServiceModel.ClientBase<DMSAPI.APISoap>, DMSAPI.APISoap
    {
        
        /// <summary>
        /// 實作此部分方法來設定服務端點。
        /// </summary>
        /// <param name="serviceEndpoint">要設定的端點</param>
        /// <param name="clientCredentials">用戶端認證</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public APISoapClient(EndpointConfiguration endpointConfiguration) : 
                base(APISoapClient.GetBindingForEndpoint(endpointConfiguration), APISoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public APISoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(APISoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public APISoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(APISoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public APISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DMSAPI.HelloWorldResponse> DMSAPI.APISoap.HelloWorldAsync(DMSAPI.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<DMSAPI.HelloWorldResponse> HelloWorldAsync()
        {
            DMSAPI.HelloWorldRequest inValue = new DMSAPI.HelloWorldRequest();
            inValue.Body = new DMSAPI.HelloWorldRequestBody();
            return ((DMSAPI.APISoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DMSAPI.LoginResponse> DMSAPI.APISoap.LoginAsync(DMSAPI.LoginRequest request)
        {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<DMSAPI.LoginResponse> LoginAsync(string userid, string password)
        {
            DMSAPI.LoginRequest inValue = new DMSAPI.LoginRequest();
            inValue.Body = new DMSAPI.LoginRequestBody();
            inValue.Body.userid = userid;
            inValue.Body.password = password;
            return ((DMSAPI.APISoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DMSAPI.LogoutResponse> DMSAPI.APISoap.LogoutAsync(DMSAPI.LogoutRequest request)
        {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<DMSAPI.LogoutResponse> LogoutAsync(string token)
        {
            DMSAPI.LogoutRequest inValue = new DMSAPI.LogoutRequest();
            inValue.Body = new DMSAPI.LogoutRequestBody();
            inValue.Body.token = token;
            return ((DMSAPI.APISoap)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DMSAPI.CallMethodResponse> DMSAPI.APISoap.CallMethodAsync(DMSAPI.CallMethodRequest request)
        {
            return base.Channel.CallMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<DMSAPI.CallMethodResponse> CallMethodAsync(DMSAPI.CallMethodParams Params)
        {
            DMSAPI.CallMethodRequest inValue = new DMSAPI.CallMethodRequest();
            inValue.Body = new DMSAPI.CallMethodRequestBody();
            inValue.Body.Params = Params;
            return ((DMSAPI.APISoap)(this)).CallMethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DMSAPI.CallMethodByStringResponse> DMSAPI.APISoap.CallMethodByStringAsync(DMSAPI.CallMethodByStringRequest request)
        {
            return base.Channel.CallMethodByStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<DMSAPI.CallMethodByStringResponse> CallMethodByStringAsync(string str)
        {
            DMSAPI.CallMethodByStringRequest inValue = new DMSAPI.CallMethodByStringRequest();
            inValue.Body = new DMSAPI.CallMethodByStringRequestBody();
            inValue.Body.str = str;
            return ((DMSAPI.APISoap)(this)).CallMethodByStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DMSAPI.GetNewDocObjResponse> DMSAPI.APISoap.GetNewDocObjAsync(DMSAPI.GetNewDocObjRequest request)
        {
            return base.Channel.GetNewDocObjAsync(request);
        }
        
        public System.Threading.Tasks.Task<DMSAPI.GetNewDocObjResponse> GetNewDocObjAsync()
        {
            DMSAPI.GetNewDocObjRequest inValue = new DMSAPI.GetNewDocObjRequest();
            inValue.Body = new DMSAPI.GetNewDocObjRequestBody();
            return ((DMSAPI.APISoap)(this)).GetNewDocObjAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DMSAPI.PLMDocObjClassResponse> DMSAPI.APISoap.PLMDocObjClassAsync(DMSAPI.PLMDocObjClassRequest request)
        {
            return base.Channel.PLMDocObjClassAsync(request);
        }
        
        public System.Threading.Tasks.Task<DMSAPI.PLMDocObjClassResponse> PLMDocObjClassAsync(DMSAPI.PLMDocObj plmDoc)
        {
            DMSAPI.PLMDocObjClassRequest inValue = new DMSAPI.PLMDocObjClassRequest();
            inValue.Body = new DMSAPI.PLMDocObjClassRequestBody();
            inValue.Body.plmDoc = plmDoc;
            return ((DMSAPI.APISoap)(this)).PLMDocObjClassAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.APISoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.APISoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.APISoap))
            {
                return new System.ServiceModel.EndpointAddress("https://cfns178.chenfull.com.tw/CF.DMS.Service/API.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.APISoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://cfns178.chenfull.com.tw/CF.DMS.Service/API.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            APISoap,
            
            APISoap12,
        }
    }
}
